AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.ksapala.rainaproximator
Globals:
  Api:
    EndpointConfiguration: REGIONAL
  Function:
    Environment:
      Variables:
        TZ: Europe/Warsaw
Resources:
  AproximateFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.ksapala.rainaproximator.aws.ApiLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://rain-aproximator/933186f7e7cc99b498feb1a80d9a2e82
      MemorySize: 2560
      Policies: AWSLambdaExecute
      Timeout: 60
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  ScanFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.ksapala.rainaproximator.aws.EventLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: s3://rain-aproximator/933186f7e7cc99b498feb1a80d9a2e82
      MemorySize: 2560
      Policies: AWSLambdaExecute
      Timeout: 60
      Events:
        ScanSchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0/5 * ? * * *)
Outputs:
  AproximateApi:
    Description: URL for application
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/aproximateKrk
    Export:
      Name: AproximateApi
